services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  mongodb1:
    image: mongo:5
    container_name: mongodb1
    ports:
      - "27017:27017"
    command: [ "mongod", "--replSet", "rs", "--bind_ip_all" ]

  mongodb2:
    image: mongo:5
    container_name: mongodb2
    command: [ "mongod", "--replSet", "rs", "--bind_ip_all" ]

  mongodb3:
    image: mongo:5
    container_name: mongodb3
    command: [ "mongod", "--replSet", "rs", "--bind_ip_all" ]

  mongo:
    image: mongo:5
    container_name: mongo

  connect:
    image: debezium/connect:latest
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - mongodb1
      - mongodb2
      - mongodb3
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      BOOTSTRAP_SERVERS: kafka:9092
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      PLUGIN_PATH: /kafka/connect
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_PLUGIN_PATH: "/kafka/connect"
    volumes:
      - ./kafka/connect:/kafka/connect
